name: admin_dashboard
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  http: ^0.13.5
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.0
  flutter_spinkit: ^5.1.0
  lottie: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  http_interceptor: ^1.0.2
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  file_picker: ^5.2.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
